# Run first: zk-single-kafka-single-ui-net-ext.yml
name: kafka-connect-s3-minio-ha

services:
  schema-registry:
    image: confluentinc/cp-schema-registry:7.7.1
    container_name: schema-registry
    ports:
      - "8081:8081"
    environment:
      SCHEMA_REGISTRY_HOST_NAME: schema-registry
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: "kafka1:9092"
    networks:
      - kafka-external-net-mn

  kafka-connect1:
    image: confluentinc/cp-kafka-connect-base:7.7.1
    container_name: kafka-connect1
    ports:
      - "8083:8083"
    environment:
      CONNECT_BOOTSTRAP_SERVERS: "kafka1:9092"
      CONNECT_REST_PORT: 8083
      CONNECT_GROUP_ID: kafka-connect
      CONNECT_CONFIG_STORAGE_TOPIC: _connect-configs
      CONNECT_OFFSET_STORAGE_TOPIC: _connect-offsets
      CONNECT_STATUS_STORAGE_TOPIC: _connect-status
      CONNECT_KEY_CONVERTER: org.apache.kafka.connect.storage.StringConverter
      CONNECT_VALUE_CONVERTER: io.confluent.connect.avro.AvroConverter
      CONNECT_VALUE_CONVERTER_SCHEMA_REGISTRY_URL: 'http://schema-registry:8081'
      CONNECT_REST_ADVERTISED_HOST_NAME: "kafka-connect1"
      CONNECT_CONFIG_STORAGE_REPLICATION_FACTOR: "1"
      CONNECT_OFFSET_STORAGE_REPLICATION_FACTOR: "1"
      CONNECT_STATUS_STORAGE_REPLICATION_FACTOR: "1"
      CONNECT_PLUGIN_PATH: /usr/share/java,/usr/share/confluent-hub-components
    volumes:
      - ./data:/data
    command:
      - bash
      - -c
      - |
        echo "Installing S3 Connector" && \
        confluent-hub install --no-prompt confluentinc/kafka-connect-s3:latest && \
        echo "Starting Kafka Connect worker" && \
        /etc/confluent/docker/run
    networks:
      - kafka-external-net-mn

  kafka-connect2:
    image: confluentinc/cp-kafka-connect-base:latest
    container_name: kafka-connect2
    ports:
      - "8084:8083" # Expose on a different host port
    environment:
      CONNECT_BOOTSTRAP_SERVERS: "kafka1:9092"
      CONNECT_REST_PORT: 8083
      CONNECT_GROUP_ID: kafka-connect
      CONNECT_CONFIG_STORAGE_TOPIC: _connect-configs
      CONNECT_OFFSET_STORAGE_TOPIC: _connect-offsets
      CONNECT_STATUS_STORAGE_TOPIC: _connect-status
      CONNECT_KEY_CONVERTER: org.apache.kafka.connect.storage.StringConverter
      CONNECT_VALUE_CONVERTER: io.confluent.connect.avro.AvroConverter
      CONNECT_VALUE_CONVERTER_SCHEMA_REGISTRY_URL: 'http://schema-registry:8081'
      CONNECT_REST_ADVERTISED_HOST_NAME: "kafka-connect2"
      CONNECT_CONFIG_STORAGE_REPLICATION_FACTOR: "1"
      CONNECT_OFFSET_STORAGE_REPLICATION_FACTOR: "1"
      CONNECT_STATUS_STORAGE_REPLICATION_FACTOR: "1"
      CONNECT_PLUGIN_PATH: /usr/share/java,/usr/share/confluent-hub-components
    volumes:
      - ./data:/data
    command:
      - bash
      - -c
      - |
        echo "Installing S3 Connector" && \
        confluent-hub install --no-prompt confluentinc/kafka-connect-s3:latest && \
        echo "Starting Kafka Connect worker" && \
        /etc/confluent/docker/run
    networks:
      - kafka-external-net-mn

  haproxy:
    image: haproxy:latest
    container_name: haproxy
    ports:
      - "8088:8080"  
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
    networks:
      - kafka-external-net-mn

  minio:
    image: quay.io/minio/minio:latest
    container_name: minio-ha
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: password12345
      MINIO_ACCESS_KEY_FILE: admin
      MINIO_SECRET_KEY_FILE: password12345
      MINIO_ROOT_USER_FILE: admin
      MINIO_ROOT_PASSWORD_FILE: password12345
    command: server --console-address ":9001" /data
    ports:
      - "9000:9000"
      - "9001:9001"
    networks:
      - kafka-external-net-mn

networks:
  kafka-external-net-mn:
    external: true
